language: node_js
cache:
  apt: true
  directories:
    - node_modules
    - $HOME/haxe/lib

sudo: false

addons:
    apt:
        packages:
            haxe

before_script:
  - mkdir -p $HOME/haxe/lib
  - haxelib setup $HOME/haxe/lib
  - haxelib install munit --always
  - haxelib install polygonal-ds --always
