# The first thing is to tell which VM environment we want the test to be run on.
# It dosen't quite matter for Haxe, just choose one of the targets our project support (e.g. PHP),
# and than apt-get install the others (e.g. Neko, C++).
# For more info, see http://about.travis-ci.org/docs/user/ci-environment/
language: node_js
cache: 
  apt: true
  directories:
    - node_modules

# Install Haxe before running the test.
before_script:
  - sudo apt-get update
  - sudo apt-get install python-software-properties -y 	# for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y      	# add the ubuntu ppa that contains haxe
  - sudo apt-get update                                	# pull info from ppa
  - sudo apt-get install haxe -y                       	# install haxe (and neko)
  - sudo haxelib setup /usr/lib/haxe/lib				# setup haxelib for dependencies
  - echo y | haxelib install targets/test.hxml			# install dependencies

# Run the test!
script:
  - grunt unit_tests

