language: node_js
cache:
  apt: true
  directories:
    - node_modules

sudo: false

addons:
    apt:
        packages:
            haxe

before_script:
  - mkdir -p $HOME/haxe/lib
  - haxelib setup $HOME/haxe/lib
  - haxelib install targets/test.hxml --always
