language: node_js
cache:
  apt: true
  directories:
    - node_modules

sudo: false

addons:
    apt:
        packages:
            haxe

before_script:
  - haxelib setup /usr/lib/haxe/lib
  - haxelib install targets/test.hxml --always
