language: haxe
cache:
  apt: true
  directories:
    - node_modules
    - $HOME/haxe/lib

sudo: false

hxml:
    - targets/test.hxml
    - targets/js.hxml

script:
    - haxelib git polygonal-ds git@github.com:polygonal/ds.git dev
    - haxelib run munit test -result-exit-code
